# Site settings
title: Alick Wong
twitter_username: alick888
name: Alick Wong

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/alick888
 - title: StackOverflow
   url: https://stackoverflow.com/users/15381388/alick-wong
 - title: DZone
   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/alickwong/
 - title: Machine Learning
   url: http://www.pegacode.com/index.php/machine-learning-sample/
   
#Any buzzword skills you want to include
skills:
 - Java
 - Python
 - C++
 - Scrum
 - Jira
 - Chef
 - Terraform
 - Ansible
 - Microservices
 - Machine Learning
 - Kubernetes
 - Docker
 - API Mangaement
 - Spring MVC/Boot/Social
 - Gradle
 - Maven
 - Subversion
 - Git
 - SQL
 - REST
 - SOA
 - Block Chain
 - MQTT
 - JMS
 - Technical Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Enterprise Architect
   start: 2018
   end: Ongoing
   employer: Pegacode
   description: Managed and developed cloud based applications using technologies provided by AliCloud.  Implemented  the cloud architecture for both development and production to provide reliable, cost effective, ready to scale and secured architecture for future growth.
 - title: Solution Architect
   start: 2011
   end: 2018
   employer: Oracle
   description: Digitized the on-premise BSS solution to integrate with cloud based products within Oracle to pave the road for a complete cloud solution for communication customers.  Architected solution guideline for application deployment including architecture framework, development guideline and go-live check-list to facilitate professional service consultant, partner and customer best practice approach in a smooth implementation process.  Resolved sticky or last minute deployment issues  to allow for customer success and building relationships with customer officials for solution expansion.
 - title: Sales Consulting Manager
   start: 2007
   end: 2011
   employer: Oracle
   description: Managed a team of 8 sales consultants to support various presales activities throughout APAC and personally engaged in key sales activities to major customers in APAC including Telkomsel and Korea Telecom (KT).
 - title: Principal Sales Consultant
   start: 2005
   end: 2007
   employer: Narus
   description: Key principal sales consultant in the APAC region to support proof of concepts, demo and solution design for network mediation and security monitoring systems for telecom.  Engaged in and provided PoCs to key customers such as China Mobile, CAT and Reliance.

#Education is required
education:
 - level: Master of Telecommunications
   date: 2007
   subject: Telecommunication
   school: HKUST
 - level: Bachelor of Science (B.Sc.)
   date: 1989
   subject: Electrical Engineering - Computer
   school: Brigham Young University, USA

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - alick888/docker-react

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/15381388/alick-wong
   flairimageurl: https://i.stack.imgur.com/6m8Pw.jpg?s=328&g=1
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
 I have extensive Solution Architecture experience for Telecom Operators, Financial Institutions and Government with in-depth knowledge in multiple programming languages including Java, Python, C++ and JavaScript.<br/><br/>  
 I am passionate about technology and innovation and have won the Innovation Award from Alibaba Cloud Global AI Innovation Challenge 2020.  <br/><br/>
 I am fluent in Agile and DevOps technologies for a complete end-to-end software life cycle that span across requirement analysis, design, build, test, deploy and monitor. <br/><br/> 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: My current role uses Python as the primary language and have been building applications in Python for the last two years.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot in addition to others. <br/><br/>
   <strong>C++</strong> I have used C++ as a language in production for ~5 years and I am familiar with many of the languages features. <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used Aliyun for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of Aliyun offerings. <br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   <strong>DevOps</strong>: I have created a CI/CD framework using Terraform, Jenkins and Ansible to deploy an enterprise software solution with applications built into Docker images running on Kubernete clusters.<br/><br/>
   <strong>Agile</strong>: I have Agile methodologies for managing customer requirements and development tasks.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as Azure/Google/AWS. <br/><br/>
   
