# Site settings
title: Alick Wong
twitter_username: alick888
name: Alick Wong

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://codingwithalickwong.blogspot.com/
 - title: GitHub
   url: https://github.com/alick888
 - title: StackOverflow
   url: https://stackoverflow.com/users/15381388/alick-wong
 - title: DZone
   url: https://dzone.com/users/4527507/alickwong.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/alickwong/
 - title: Machine Learning
   url: http://www.pegacode.com/index.php/machine-learning-sample/
   
#Any buzzword skills you want to include
skills:
 - Java
 - Python
 - C++
 - Scrum
 - Jira
 - Chef
 - Terraform
 - Ansible
 - Microservices
 - Machine Learning
 - Kubernetes
 - Docker
 - API Mangaement
 - Spring MVC/Boot/Social
 - Gradle
 - Maven
 - Subversion
 - Git
 - SQL
 - REST
 - SOA
 - Block Chain
 - MQTT
 - JMS
 - Technical Architecture

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://codingwithalickwong.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Enterprise Architect
   start: 2018
   end: Ongoing
   employer: Pegacode
   description: Designed and implemented cloud native application frameworks using Python and Java for IoT and Finance industry.  Managed cloud based architecture for hosting application development and production environments.
 - title: Solution Architect
   start: 2007
   end: 2018
   employer: Oracle
   description: Designed and developed integration framework for B/OSS products in the cloud and on-premise.  Created automated deployment framework for B/OSS applications based on modern CI/CD technologies as part of the integrated product offerings.  Provided best practice guideline and expert services for customer implementations.
 - title: Principal Sales Consultant
   start: 2000
   end: 2007
   employer: Portal Software
   description: Key principal sales consultant in the APAC region to support proof of concepts, demo and solution design for B/OSS systems written in C++ and Java.
 - title: Systems Architect
   start: 1995
   end: 2000
   employer: Hong Kong Police
   description: Designed and implemented an integration solution with single sign-on and end-to-end encryption for HKP applications.
 - title: Systems Analysts
   start: 1989
   end: 1995
   employer: Chase Manhattan Bank
   description: Designed and implemented a FX Margin system implemented in IBM mainframe in Hong Kong and Sun Solaris in New York.

#Education is required
education:
 - level: Master of Telecom
   date: 2007
   subject: Telecommunication
   school: HKUST
 - level: Bachelor of Science (B.Sc.)
   date: 1989
   subject: Electrical Engineering - Computer
   school: Brigham Young University, USA

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - alick888/DAppCentral
 - alick888/faceplusplus
 - alick888/mule-modules-sayhi
 - alick888/docker-react

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/15381388/alick-wong
   flairimageurl: https://stackoverflow.com/users/flair/15381388.png

intro: |
 I have extensive Solution Architecture experience for Telecom Operators, Financial Institutions and Government with in-depth knowledge in multiple programming languages including Java, Python, C++ and JavaScript.<br/><br/>  
 I am passionate about technology and innovation and have won the Innovation Award from Alibaba Cloud Global AI Innovation Challenge 2020.  <br/><br/>
 I am fluent in Agile and DevOps technologies for a complete end-to-end software life cycle that span across requirement analysis, design, build, test, deploy and monitor. <br/><br/> 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: My current role uses Python as the primary language and have been building applications in Python for the last two years.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot in addition to others. <br/><br/>
   <strong>C++</strong> I have used C++ as a language in production for ~5 years and I am familiar with many of the languages features. <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used Aliyun for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of Aliyun offerings. <br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used Flask, Django, jQuery, Bootstrap and React<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   <strong>DevOps</strong>: I have created a CI/CD framework using Terraform, Jenkins and Ansible to deploy an enterprise software solution with applications built into Docker images running on Kubernete clusters.<br/><br/>
   <strong>Agile</strong>: I have used Agile methodologies for managing customer requirements and development tasks.<br/><br/>
   <strong>BlockChain</strong>: I have used in some personal projects to record authentic transaction using Smart Contract, DApp and IPFS.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, Machine Learning Model, a variety of social APIs (Twilio, Slack, etc) and cloud platforms such as Azure/Google/AWS. <br/><br/>
   
